source 'https://rubygems.org'
ruby '2.1.2'

gem 'rails', '4.2.1'

# server
gem 'puma'

# model
gem 'active_hash'

# markup
gem 'sass-rails', '~> 5.0'
gem 'slim-rails'
gem 'jquery-rails'

gem 'uglifier', '>= 1.3.0'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# cron
gem 'whenever', :require => false

# push notification
gem 'apns'

# crawling
gem 'yasuri'
gem 'simple-rss'

group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'heroku'
end

group :test do
  gem 'autodoc'
  gem 'redcarpet'
end

group :production do
  gem 'pg'
  gem 'activerecord-postgresql-adapter'
end
